### ISSUE TITLE
encoder example doesn't seem to work

### ISSUE THREAD

**Issue by ben0x539** [PistonDevelopers/image-gif#19]
The generated `target/beacon.gif` doesn't seem to be accepted as a valid file by either firefox or chromium, or by the `Decoder` (`Format("Image truncated")` on reading the first frame, tried it like this: https://gist.github.com/ben0x539/616e5e568d24edffefb8).

**Comment by nwin** [comment]
Thanks for reporting. This is a consequence of #16.
