### ISSUE TITLE
Type-safe pixel format

### ISSUE THREAD

**Issue by pornel** [PistonDevelopers/image-gif#35]
`Frame.buffer` is a `Cow<'a, [u8]>`. Even if I set pixel type to be RGBA, I still have to deal with a slice of `u8`.

I would prefer if type system was used to ensure the right pixel format, e.g.

```rust
let reader: gif::Reader<_, pixel::RGBA> = decoder.read_info();
```

which would return `Frame<RGBA>` with `Cow<'a, [RGBA]>`.

**Comment by nwin** [comment]
Will be fixed via #33.
