### ISSUE TITLE
How to save a gif to file system

### ISSUE THREAD

**Issue by franleplant** [PistonDevelopers/image-gif#6]
Hi!
    Im creating a RGBA frame from a RGBA image generated with the `image` module:

```rust
    let mut img = generateRgbaImage();

    // Create frame from data
    let frame = gif::Frame::from_rgba(N as u16, M as u16, &mut *img);
    // Create encoder
    let mut image = Vec::new();
    let encoder = gif::Encoder::new(&mut image, N as u16, M as u16);
    // Write header to file
    let mut encoder = encoder.write_global_palette(&[]).unwrap();
    // Write frame to file
    encoder.write_frame(&frame).unwrap();
```

This compiles ok, but it keeps running without an end.
And also I dont know how to write the resulting gif into a file.

Thanks a lot!

Fran

**Comment by nwin** [comment]
As you are using image anyway: There are convenient methods on the image buffer. Probably called save or so, I don't recall the name. 

Concerning speed, depending on the size of the image it could take a while, did you build with optimizations on i.e. using --release? If it still doesn't work I'll need to look further into it. Could you then please a more complete example such that I can reproduce the issue?

For writing to a file just replace the output-Vec with a file, I agree the example given in the docs should be adapted.

**Comment by franleplant** [comment]
Thanks @nwin , this is how I managed to make it work:

```diff

// Create frame from data
let frame = gif::Frame::from_rgba(N as u16, M as u16, &mut *img);
// Create encoder
- let mut image = Vec::new();
+ let ref mut fout = File::create(&Path::new("fractal.gif")).unwrap();
- let encoder = gif::Encoder::new(&mut image, N as u16, M as u16);
+ let encoder = gif::Encoder::new(&mut *fout, N as u16, M as u16);
// Write header to file
let mut encoder = encoder.write_global_palette(&[]).unwrap();
// Write frame to file
encoder.write_frame(&frame).unwrap();
```

Navigating through the docs is kind of confusing until you get used to them, and this include the `image` package as well.

Thanks for your help!
Fran
